/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package EarthSim.GUI;
import java.awt.Dimension;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author tbaxter
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new Dimension(800, 600));
        setMinimumSize(new Dimension(800, 600));
        setPreferredSize(new Dimension(800, 600));
        GridBagLayout gridBagLayout = new GridBagLayout();
        gridBagLayout.columnWidths = new int[]{137, 60, 51, 195, 75, 80, 40, 32, 16, 75, 0};
        gridBagLayout.rowHeights = new int[]{436, 28, 30, 0};
        gridBagLayout.columnWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
        gridBagLayout.rowWeights = new double[]{0.0, 0.0, 0.0, Double.MIN_VALUE};
        getContentPane().setLayout(gridBagLayout);
        jLabel1 = new javax.swing.JLabel();
        
                jLabel1.setText("Grid Spacing:");
                GridBagConstraints gbc_jLabel1 = new GridBagConstraints();
                gbc_jLabel1.anchor = GridBagConstraints.EAST;
                gbc_jLabel1.insets = new Insets(0, 0, 5, 5);
                gbc_jLabel1.gridx = 0;
                gbc_jLabel1.gridy = 1;
                getContentPane().add(jLabel1, gbc_jLabel1);
        tfGridSpacing = new javax.swing.JTextField();
        GridBagConstraints gbc_tfGridSpacing = new GridBagConstraints();
        gbc_tfGridSpacing.anchor = GridBagConstraints.NORTH;
        gbc_tfGridSpacing.fill = GridBagConstraints.HORIZONTAL;
        gbc_tfGridSpacing.insets = new Insets(0, 0, 5, 5);
        gbc_tfGridSpacing.gridx = 1;
        gbc_tfGridSpacing.gridy = 1;
        getContentPane().add(tfGridSpacing, gbc_tfGridSpacing);
        jLabel4 = new javax.swing.JLabel();
        
                jLabel4.setText("degrees");
                GridBagConstraints gbc_jLabel4 = new GridBagConstraints();
                gbc_jLabel4.anchor = GridBagConstraints.WEST;
                gbc_jLabel4.insets = new Insets(0, 0, 5, 5);
                gbc_jLabel4.gridx = 2;
                gbc_jLabel4.gridy = 1;
                getContentPane().add(jLabel4, gbc_jLabel4);
        jLabel3 = new javax.swing.JLabel();
        
                jLabel3.setText("Presentation Display Rate:");
                GridBagConstraints gbc_jLabel3 = new GridBagConstraints();
                gbc_jLabel3.anchor = GridBagConstraints.EAST;
                gbc_jLabel3.insets = new Insets(0, 0, 5, 5);
                gbc_jLabel3.gridwidth = 3;
                gbc_jLabel3.gridx = 4;
                gbc_jLabel3.gridy = 1;
                getContentPane().add(jLabel3, gbc_jLabel3);
        tfDisplayRate = new javax.swing.JTextField();
        GridBagConstraints gbc_tfDisplayRate = new GridBagConstraints();
        gbc_tfDisplayRate.anchor = GridBagConstraints.NORTH;
        gbc_tfDisplayRate.fill = GridBagConstraints.HORIZONTAL;
        gbc_tfDisplayRate.insets = new Insets(0, 0, 5, 0);
        gbc_tfDisplayRate.gridwidth = 2;
        gbc_tfDisplayRate.gridx = 8;
        gbc_tfDisplayRate.gridy = 1;
        getContentPane().add(tfDisplayRate, gbc_tfDisplayRate);
        jLabel2 = new javax.swing.JLabel();
        
                jLabel2.setText("Simulation Time Step:");
                GridBagConstraints gbc_jLabel2 = new GridBagConstraints();
                gbc_jLabel2.anchor = GridBagConstraints.WEST;
                gbc_jLabel2.insets = new Insets(0, 0, 0, 5);
                gbc_jLabel2.gridx = 0;
                gbc_jLabel2.gridy = 2;
                getContentPane().add(jLabel2, gbc_jLabel2);
        tfTimeStep = new javax.swing.JTextField();
        GridBagConstraints gbc_tfTimeStep = new GridBagConstraints();
        gbc_tfTimeStep.anchor = GridBagConstraints.NORTH;
        gbc_tfTimeStep.fill = GridBagConstraints.HORIZONTAL;
        gbc_tfTimeStep.insets = new Insets(0, 0, 0, 5);
        gbc_tfTimeStep.gridx = 1;
        gbc_tfTimeStep.gridy = 2;
        getContentPane().add(tfTimeStep, gbc_tfTimeStep);
        jLabel5 = new javax.swing.JLabel();
        
                jLabel5.setText("minutes");
                GridBagConstraints gbc_jLabel5 = new GridBagConstraints();
                gbc_jLabel5.anchor = GridBagConstraints.WEST;
                gbc_jLabel5.insets = new Insets(0, 0, 0, 5);
                gbc_jLabel5.gridx = 2;
                gbc_jLabel5.gridy = 2;
                getContentPane().add(jLabel5, gbc_jLabel5);
        btnStart = new javax.swing.JButton();
        btnStart.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		validateInput();
        		
        		//TODO - Start the simulation
        	}
        });
        
                btnStart.setLabel("Start");
                GridBagConstraints gbc_btnStart = new GridBagConstraints();
                gbc_btnStart.anchor = GridBagConstraints.SOUTHWEST;
                gbc_btnStart.insets = new Insets(0, 0, 0, 5);
                gbc_btnStart.gridx = 4;
                gbc_btnStart.gridy = 2;
                getContentPane().add(btnStart, gbc_btnStart);
        btnPause = new javax.swing.JButton();
        btnPause.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	
        		//TODO - Pause the simulation
        	}
        });
        
                btnPause.setText("Pause");
                GridBagConstraints gbc_btnPause = new GridBagConstraints();
                gbc_btnPause.anchor = GridBagConstraints.SOUTHWEST;
                gbc_btnPause.insets = new Insets(0, 0, 0, 5);
                gbc_btnPause.gridx = 5;
                gbc_btnPause.gridy = 2;
                getContentPane().add(btnPause, gbc_btnPause);
        btnRestart = new javax.swing.JButton();
        btnRestart.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	
        		validateInput();
        		
        		//TODO - Restart the simulation
        	}
        });
        
                btnRestart.setText("Restart");
                GridBagConstraints gbc_btnRestart = new GridBagConstraints();
                gbc_btnRestart.anchor = GridBagConstraints.SOUTHWEST;
                gbc_btnRestart.insets = new Insets(0, 0, 0, 5);
                gbc_btnRestart.gridwidth = 3;
                gbc_btnRestart.gridx = 6;
                gbc_btnRestart.gridy = 2;
                getContentPane().add(btnRestart, gbc_btnRestart);
        btnStop = new javax.swing.JButton();
        btnStop.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	
        		//TODO - Stop the simulation
        	}
        });
        
                btnStop.setText("Stop");
                GridBagConstraints gbc_btnStop = new GridBagConstraints();
                gbc_btnStop.anchor = GridBagConstraints.SOUTHWEST;
                gbc_btnStop.gridx = 9;
                gbc_btnStop.gridy = 2;
                getContentPane().add(btnStop, gbc_btnStop);

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    
    private void validateInput() {
    	
    	
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnRestart;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tfDisplayRate;
    private javax.swing.JTextField tfGridSpacing;
    private javax.swing.JTextField tfTimeStep;
    // End of variables declaration                   
}
