/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package EarthSim.GUI;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

import EarthSim.Presentation.Presentation;

/**
 *
 * @author tbaxter
 */
public class MainWindow extends javax.swing.JFrame {	
	
	/**
	 * Required GUI ID
	 */
	private static final long serialVersionUID = 1L;
	
	long startTime = 0;
	long endTime = 0;
	long startPauseTime = 0;
	long endPauseTime = 0;
	long totalPausedTime = 0;
	
	private GUIState _state = GUIState.IDLE;
	
	/**
	 * Creates new form MainWindow
	 */
	public MainWindow() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setMaximumSize(new Dimension(800, 600));
		setMinimumSize(new Dimension(800, 600));
		setPreferredSize(new Dimension(800, 600));

		getContentPane().setLayout(null);

		presentation = new Presentation(new Dimension(800, 600), new Dimension(800, 600), new Dimension(800, 600));
		presentation.getEarthPanel().setBounds(5, 0, 800, 515);
		getContentPane().add(presentation.getEarthPanel());


		//        panel = new JPanel();
		//        panel.setBounds(0, 0, 800, 515);
		//        panel.setLayout(null);

		//        getContentPane().add(panel);
		jLabel1 = new javax.swing.JLabel();
		jLabel1.setBounds(59, 521, 83, 16);
		jLabel1.setHorizontalAlignment(SwingConstants.RIGHT);

		jLabel1.setText("Grid Spacing:");
		getContentPane().add(jLabel1);
		tfGridSpacing = new javax.swing.JTextField();
		tfGridSpacing.setText("15");
		tfGridSpacing.setBounds(147, 515, 55, 28);
		getContentPane().add(tfGridSpacing);
		jLabel4 = new javax.swing.JLabel();
		jLabel4.setBounds(207, 521, 49, 16);

		jLabel4.setText("degrees");
		getContentPane().add(jLabel4);
		jLabel3 = new javax.swing.JLabel();
		jLabel3.setBounds(494, 521, 164, 16);

		jLabel3.setText("Presentation Display Rate:");
		getContentPane().add(jLabel3);
		tfDisplayRate = new javax.swing.JTextField();
		tfDisplayRate.setBounds(695, 515, 105, 28);
		getContentPane().add(tfDisplayRate);
		jLabel2 = new javax.swing.JLabel();
		jLabel2.setBounds(0, 555, 137, 16);
		jLabel2.setHorizontalAlignment(SwingConstants.RIGHT);

		jLabel2.setText("Simulation Time Step:");
		getContentPane().add(jLabel2);
		tfTimeStep = new javax.swing.JTextField();
		tfTimeStep.setText("1");
		tfTimeStep.setBounds(147, 548, 55, 28);
		getContentPane().add(tfTimeStep);
		jLabel5 = new javax.swing.JLabel();
		jLabel5.setBounds(207, 555, 51, 16);

		jLabel5.setText("minutes");
		getContentPane().add(jLabel5);
		btnStart = new javax.swing.JButton();
		btnStart.setBounds(458, 549, 75, 29);
		btnStart.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				
				validateInput();
				
				startSimulation();
			}
		});

		btnStart.setText("Start");
		getContentPane().add(btnStart);
		btnPause = new javax.swing.JButton();
		btnPause.setBounds(538, 549, 80, 29);
		btnPause.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				pauseSimulation();
			}
		});

		btnPause.setText("Pause");
		getContentPane().add(btnPause);
		btnRestart = new javax.swing.JButton();
		btnRestart.setBounds(623, 549, 88, 29);
		btnRestart.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				validateInput();
				
				restartSimulation();
			}
		});

		btnRestart.setText("Restart");
		getContentPane().add(btnRestart);
		btnStop = new javax.swing.JButton();
		btnStop.setBounds(725, 549, 75, 29);
		btnStop.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {							
				stopSimulation();
			}
		});

		btnStop.setText("Stop");
		getContentPane().add(btnStop);
		
		// Set default button states
		btnStart.setEnabled(true);
		btnPause.setEnabled(false);
		btnRestart.setEnabled(false);
		btnStop.setEnabled(false);

		pack();
	}// </editor-fold>                        

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainWindow().setVisible(true);
			}
		});
	}
	
	/**
	 * Starts the simulation
	 */
	private void startSimulation() {
		
		if(_state == GUIState.IDLE) {		
			endTime = 0;					
			totalPausedTime = 0;
			startPauseTime = 0;
			endPauseTime = 0;
			startTime = System.currentTimeMillis();
			
			//TODO - Start the simulation
			
		}
		else if(_state == GUIState.PAUSED) {																				
			endPauseTime = System.currentTimeMillis();
			totalPausedTime += (endPauseTime - startPauseTime);			
			
			
			//TODO - Resume the simulation
			
		}									
		
		btnStart.setEnabled(false);
		btnPause.setEnabled(true);
		btnStop.setEnabled(false);
		btnRestart.setEnabled(true);
		
		_state = GUIState.RUNNING;
	}
	
	/**
	 * Pauses the simulation
	 */
	private void pauseSimulation() {
		
		startPauseTime = System.currentTimeMillis();
		endPauseTime = 0;
		//TODO - Pause the simulation
		
		
		btnStart.setEnabled(true);
		btnPause.setEnabled(false);
		btnStop.setEnabled(true);
		btnRestart.setEnabled(true);
		
		_state = GUIState.PAUSED;
	}
	
	/**
	 * Restarts the simulation
	 */
	private void restartSimulation() {
		
		endTime = 0;				
		totalPausedTime = 0;
		startPauseTime = 0;
		endPauseTime = 0;
		
		startTime = System.currentTimeMillis();

		//TODO - Restart the simulation
		
		
		btnStart.setEnabled(false);
		btnPause.setEnabled(true);
		btnStop.setEnabled(true);
		btnRestart.setEnabled(true);
		
		_state = GUIState.RUNNING;
	}
	
	/**
	 * Stops the simulation
	 */
	private void stopSimulation() {
		
		//TODO - Stop the simulation
		
		
		endTime = System.currentTimeMillis();
		
		// Get memory usage
		Runtime runtime = Runtime.getRuntime(); //runtime (runtime?)
		runtime.gc();
		long memory = runtime.totalMemory() - runtime.freeMemory();
		System.out.println("Used memory in bytes is: " + memory);
		
		System.out.println("Total simulation time in ms is :" + (endTime - startTime));
		
		btnStart.setEnabled(true);
		btnPause.setEnabled(false);
		btnStop.setEnabled(false);
		btnRestart.setEnabled(false);
		
		_state = GUIState.IDLE;
		
		endTime = 0;
		startTime = 0;
		totalPausedTime = 0;
		startPauseTime = 0;
		endPauseTime = 0;
	}

	/**
	 * Validates user input on the form
	 */
	private boolean validateInput() {

		// Check valid input
		if(!isValidInt(tfDisplayRate.getText())) {
			JOptionPane.showMessageDialog(null, "Display rate must be a valid integer value");
			return false;
		}

		if(!isValidInt(tfGridSpacing.getText())) {
			JOptionPane.showMessageDialog(null, "Grid spacing must be a valid integer value");
			return false;
		}

		if(!isValidInt(tfTimeStep.getText())) {
			JOptionPane.showMessageDialog(null, "Time step must be a valid integer value");
			return false;
		}

		// Check for valid business logic input
		if(Integer.parseInt(tfDisplayRate.getText()) < 0) {
			//TODO - validate display rate
		}

		if(Integer.parseInt(tfGridSpacing.getText()) < 1 || Integer.parseInt(tfGridSpacing.getText()) > 180) {
			JOptionPane.showMessageDialog(null, "Grid spacing must be between 1 and 180 degrees");
			return false;
		}

		if(Integer.parseInt(tfTimeStep.getText()) < 1 || Integer.parseInt(tfTimeStep.getText()) > 1440) {
			JOptionPane.showMessageDialog(null, "Time step must be between 1 and 1440 minutes (1 day)");
			return false;
		}

		return true;

	}

	/**
	 * Checks if string is a valid integer value
	 * 
	 * @param intString a {@code String} containing the input to be validated
	 * @return true if input can be parsed into a valid integer
	 */
	private boolean isValidInt(String intString) {

		try {
			Integer.parseInt(intString);
			return true;
		} catch (NumberFormatException ex) {
			return false;
		}
	}
	
	/**
	 * Gets the current state of the program
	 * 
	 * @return current state of the program
	 */
	public GUIState getGUIState() {
		return _state;
	}
		
	// Variables declaration - do not modify                     
	private javax.swing.JButton btnPause;
	private javax.swing.JButton btnRestart;
	private javax.swing.JButton btnStart;
	private javax.swing.JButton btnStop;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JTextField tfDisplayRate;
	private javax.swing.JTextField tfGridSpacing;
	private javax.swing.JTextField tfTimeStep;
	private JPanel panel;
	private Presentation presentation;
	// End of variables declaration         
	
	public enum GUIState {		
		IDLE,
		RUNNING,
		PAUSED				
	}
}
